version: '3.7'
services:
  # App service
  # demoapp:
  #   depends_on:
  #     - db
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: elastic-docker
  #   container_name: demoapp
  #   restart: always
  #   tty: true
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   working_dir: /var/www/elastic
  #   environment:
  #     SERVICE_NAME: demoapp
  #     SERVICE_TAGS: dev
  #     SERVICE_DB_HOST: ${DATABASE_HOST}:${DATABASE_PORT}
  #     SERVICE_DB_USER: ${DATABASE_USERNAME}
  #     SERVICE_DB_PASSWORD: ${DATABASE_PASSWORD}
  #     SERVICE_ES_HOST: ${ELASTIC_SEARCH_HOST}:${ELASTIC_SEARCH_PORT}
  #     ELASTICSEARCH_URL: ${ELASTIC_SEARCH_URL}
  #   volumes:
  #     - ./:/var/www/elastic
  #     - /var/www/elastic/node_modules

  # Database service
  database:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db_data:/data/db
    ports:
      - '27017:27017'

  # Elastic search service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - http.port=9200
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/var/lib/elasticsearch
    ports:
      - ${ELASTIC_SEARCH_PORT}:${ELASTIC_SEARCH_PORT}

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_SEARCH_URL}
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  db_data:
  es_data:

networks:
  elastic-network:
    driver: bridge
